---
- name: Increase UDP buffers
  shell:
    cmd: |
      bash -c "cat >/etc/sysctl.d/20-solana-udp-buffers.conf <<EOF
      # Increase UDP buffer size
      net.core.rmem_default = 134217728
      net.core.rmem_max = 134217728
      net.core.wmem_default = 134217728
      net.core.wmem_max = 134217728
      EOF"
  become: yes

- name: Enable UDP buffers
  shell:
    cmd: |
      sysctl -p /etc/sysctl.d/20-solana-udp-buffers.conf
  become: yes